//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento
    {
        public int idCodigo { get; set; }
        public string codigoProducto { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public Nullable<System.DateTime> creacionRegistro { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> tipoMovimiento { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public Nullable<int> sobrante { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual producto producto { get; set; }
    }
}
