//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appInventory.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.movimiento = new HashSet<movimiento>();
        }
        [Required(ErrorMessage = "El código es obligatorio.")]
        public string codigoProducto { get; set; }
        [Required(ErrorMessage = "El nombre del producto es obligatorio.")]

        public string nombreProducto { get; set; }
        [Required(ErrorMessage = "La cantidad es obligatorio.")]

        public Nullable<int> cantidad { get; set; }
        [Required(ErrorMessage = "La categoria es obligatorio.")]

        public string categoriaId { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento> movimiento { get; set; }
    }
}
